version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: quarkus
      POSTGRES_DB: clients_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network

  quarkus-api:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: quarkus-client-api
    environment:
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_USERNAME: quarkus
      QUARKUS_DATASOURCE_PASSWORD: quarkus
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/clients_db
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: validate
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  pg_data:

networks:
  app-network:
