services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: quarkus
      POSTGRES_DB: customers_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U quarkus -d customers_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  quarkus-api:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: quarkus-customers-api
    environment:
      QUARKUS_PROFILE: docker
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_USERNAME: quarkus
      QUARKUS_DATASOURCE_PASSWORD: quarkus
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/customers_db
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: validate
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./logs:/deployments/logs

volumes:
  pg_data:

networks:
  app-network:
